SELECT *
FROM customer_behavior
LIMIT 10;


-- What is the total revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount) as revenue
FROM customer_behavior
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer_behavior
WHERE discount_applied = 'Yes'
	AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behavior);

-- Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS avg_rev_rating
FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg_rev_rating DESC
LIMIT 5;

-- Compare the average purchase amounts between standard and express shipping

SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS total_purchases
FROM customer_behavior
WHERE shipping_type = 'Express' OR shipping_type = 'Standard'
GROUP BY shipping_type
ORDER BY total_purchases DESC;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers

SELECT subscription_status, COUNT(customer_id) AS customers, ROUND(AVG(purchase_amount),2) AS avg_spend, SUM(purchase_amount) AS total_amount
FROM customer_behavior
GROUP BY subscription_status;

-- Which 5 producst have the highest percentage of purchases with discount applied?

SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into new, returning, and loyal based on theri
-- total number of previous purchases and show the count of each segment

WITH customer_type AS (
SELECT customer_id, previous_purchases, 
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	WHEN previous_purchases > 10 THEN 'Loyal'
	END AS customer_segment
FROM customer_behavior)

SELECT customer_segment, COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment;

-- What are top 3 most purchased products within each category

WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) AS item_rank
FROM customer_behavior
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3

-- Are customers who are repeat buyers (more than 5 prev purchases) also likely to subscribe?

SELECT COUNT(customer_id) AS customer_amount, 
ROUND(100 * SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END)/COUNT(subscription_status),2) as subscription_rate
FROM customer_behavior
WHERE previous_purchases > 5
;

-- What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(SUM(purchase_amount) * 100.0 / SUM(SUM(purchase_amount)) OVER (),2) AS revenue_percentage
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;